name: 'KMMBridge: Remote SPM Publishing Support'
description: 'Publish KMP SPM builds to a remote repo'
author: 'Kevin Galligan'

branding:
  icon: 'external-link'
  color: 'orange'

inputs:
  commitMessage:
    description: 'Message for the commit which updates the `Package.swift` file.'
    required: true
  tagMessage:
    description: 'Message for the version tag commit. Defaults to "Version ${tagVersion}".'
    required: false
  tagVersion:
    description: 'Version string to use in the tag. Should follow semver rules: https://semver.org/.'
    required: true
  remoteRepo:
    description: 'Repo we are publishing to in [org]/[repo] format.'
    required: true
  remoteBranch:
    description: 'Branch we are pushing to.'
    required: true
  remoteRepoUrl:
    description: 'Full url for the repo we are publishing to. Defaults to "https://github.com/${remoteRepo}.git".'
    required: false
  localPackagePath:
    description: 'Local path to Package.swift'
    required: false
  remotePackagePath:
    description: 'Remote path to Package.swift'
    required: false

runs:
  using: node20
  main: dist/index.js
